### PR TITLE
Support previous titles at the same company (#515)

### PR DESCRIPTION
**Pull request by rachelslurs**
I ended up removing the calendar icon. @colinhemphill let me know if you have any thoughts on that. I just figured it looked funny for all of the previous titles.

### CODE REVIEW

**Comment by colinhemphill** [comment]
@rachelslurs This is a great idea! I'll take a look at it more closely this weekend and might fiddle with the design of it a little.

In the meantime, my goal with this generator is to have 100% parity between the web version and the PDF. Can you potentially get the previous titles in the PDF layout?

**Comment by rachelslurs** [comment]
@colinhemphill great! I will work on this in the coming few days.

**Comment by rachelslurs** [comment]
@colinhemphill I had to take off a bit of the lorem ipsum to keep it to the single page, but I did it. 🙂

**Comment by colinhemphill** [comment]
@rachelslurs Just got back from vacation, but looks good to me! I might toy with the design a bit after landing this, but thanks for adding a really helpful feature.

**Pull request merged**
